### ISSUE TITLE
BottomNavigation 맨 우측 설정버튼 연속 클릭 시 앱 팅김 오류

### ISSUE THREAD

**Issue by BeomjunSon** [LEE2525/subwiki#6]
2019-04-17 16:44:17.213 26604-26633/com.example.subwiki E/eglCodecCommon: glUtilsParamSize: unknow param 0x00008cdf
2019-04-17 16:44:17.214 26604-26633/com.example.subwiki E/eglCodecCommon: glUtilsParamSize: unknow param 0x00008cdf
2019-04-17 16:44:17.214 26604-26633/com.example.subwiki E/eglCodecCommon: glUtilsParamSize: unknow param 0x00008824
2019-04-17 16:44:17.214 26604-26633/com.example.subwiki E/eglCodecCommon: glUtilsParamSize: unknow param 0x00008824
2019-04-17 16:44:32.670 26604-26604/com.example.subwiki E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.subwiki, PID: 26604
    android.view.InflateException: Binary XML file line #2: Binary XML file line #2: Error inflating class fragment
    Caused by: android.view.InflateException: Binary XML file line #2: Error inflating class fragment
    Caused by: java.lang.IllegalArgumentException: Binary XML file line #2: Duplicate id 0x7f0900a0, tag null, or parent id 0x7f09004b with another fragment for com.beomsa.subwiki.SettingPreferenceFragment
        at android.app.FragmentManagerImpl.onCreateView(FragmentManager.java:3615)
        at android.app.FragmentController.onCreateView(FragmentController.java:98)
        at android.app.Activity.onCreateView(Activity.java:6187)
        at androidx.fragment.app.FragmentActivity.onCreateView(FragmentActivity.java:389)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:780)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at com.beomsa.subwiki.SettingsActivity.onCreateView(SettingsActivity.java:24)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2439)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:802)
        at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
        at androidx.fragment.app.FragmentManagerImpl$1.run(FragmentManager.java:733)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by leejooy96** [comment]
bd8ac4f 해결됨
