### ISSUE TITLE
Board 게시판에서 우측 하단 아이콘 클릭시 에러

### ISSUE THREAD

**Issue by BeomjunSon** [LEE2525/subwiki#7]
java.lang.IllegalArgumentException: java.lang.ClassCastException@69da8b10
	at sun.reflect.GeneratedMethodAccessor503.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at android.animation.PropertyValuesHolder_Delegate.callMethod(PropertyValuesHolder_Delegate.java:108)
	at android.animation.PropertyValuesHolder_Delegate.nCallFloatMethod(PropertyValuesHolder_Delegate.java:143)
	at android.animation.PropertyValuesHolder.nCallFloatMethod(PropertyValuesHolder.java)
	at android.animation.PropertyValuesHolder.access$400(PropertyValuesHolder.java:38)
	at android.animation.PropertyValuesHolder$FloatPropertyValuesHolder.setAnimatedValue(PropertyValuesHolder.java:1387)
	at android.animation.ObjectAnimator.animateValue(ObjectAnimator.java:990)
	at android.animation.ValueAnimator.animateBasedOnTime(ValueAnimator.java:1339)
	at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1471)
	at android.animation.ValueAnimator.pulseAnimationFrame(ValueAnimator.java:1490)
	at android.animation.AnimatorSet.pulseFrame(AnimatorSet.java:1163)
	at android.animation.AnimatorSet.handleAnimationEvents(AnimatorSet.java:1146)
	at android.animation.AnimatorSet.doAnimationFrame(AnimatorSet.java:1046)
	at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
	at android.animation.AnimationHandler.access$100(AnimationHandler.java:37)
	at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:947)
	at android.view.Choreographer.doCallbacks(Choreographer.java:761)
	at android.view.Choreographer_Delegate.doFrame(Choreographer_Delegate.java:66)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.renderAndBuildResult(RenderSessionImpl.java:563)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.render(RenderSessionImpl.java:425)
	at com.android.layoutlib.bridge.BridgeRenderSession.render(BridgeRenderSession.java:120)
	at com.android.ide.common.rendering.api.RenderSession.render(RenderSession.java:151)
	at com.android.ide.common.rendering.api.RenderSession.render(RenderSession.java:133)
	at com.android.tools.idea.rendering.RenderTask.lambda$null$8(RenderTask.java:755)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by leejooy96** [comment]
해결
